language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-22.0.1
    - android-22
    
before_script:
  - echo yes | android update sdk --no-ui --all --filter platform-tools,tools
  - echo yes | android update sdk --no-ui --all --filter build-tools-22.0.1
  - echo yes | android update sdk --no-ui --all --filter android-22

script:
    - ./gradlew clean test
